[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wxo-clients"
version = "0.1.0"
description = "IBM watsonx.orchestrate SDK"
authors = [
    { name = "IBM", email = "support@ibm.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2024.8.30",
    "importlib-metadata>=8.5.0",
    "packaging>=24.2",
    "requests>=2.32.3",
    "tabulate>=0.9.0",
    "urllib3>=2.2.3",
]

[tool.setuptools.packages.find]
where = ["ibm_watsonx_orchestrate"]