import asyncio
import logging
from pathlib import Path

from examples.flow_builder.count_tracker_flow.tools.count_tracker_flow import build_count_tracker_flow

logger = logging.getLogger(__name__)

flow_run = None


def on_flow_end(result):
    """Callback when the flow completes."""
    print(f"Custom Handler: flow `{flow_run.name}` completed with result: {result}")


def on_flow_error(error):
    """Callback when the flow fails."""
    print(f"Custom Handler: flow `{flow_run.name}` failed: {error}")


async def main():
    """Build the count tracker flow, save the spec, and invoke it.

    Note: the correlation_id is generated by the runtime on each invoke() call
    and cannot be controlled from here. Each run therefore gets a fresh agent
    thread and the count resets to 1 each time.
    To see the count increment (1 → 2 → 3 …) use the Chat UI within the same
    session — the UI maintains a stable correlation context across calls.
    """
    my_flow_definition = await build_count_tracker_flow().compile_deploy()

    generated_folder = f"{Path(__file__).resolve().parent}/generated"
    Path(generated_folder).mkdir(parents=True, exist_ok=True)
    my_flow_definition.dump_spec(f"{generated_folder}/count_tracker_flow.json")

    global flow_run
    flow_run = await my_flow_definition.invoke(
        {},
        on_flow_end_handler=on_flow_end,
        on_flow_error_handler=on_flow_error,
        debug=True,
    )


if __name__ == "__main__":
    asyncio.run(main())
