services:
########################
# Orchestrate Lite dependencies
########################
  wxo-server-db:
    image: us.icr.io/watson-orchestrate-private/wxo-server-db:${DBTAG:-latest}
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d postgres
      interval: 5s
      timeout: 60s
      retries: 20
    volumes:
      - wxo-server-db:/var/lib/postgresql/data
      - wxo-applied-migrations:/var/lib/postgresql/applied_migrations
    command: -c shared_preload_libraries=pgsodium

    
volumes:
  tools:
    driver: local
  wxo-server-redis-data:
    driver: local
  wxo-server-db:
    driver: local
  wxo-applied-migrations:
    driver: local
  wxo-server-minio-data:
    driver: local
  wxo-milvus-data:
    driver: local
  wxo-milvus-etcd-data:
    driver: local
  ui-data:
    driver: local
  tools-runtime-data:
    driver: local
  langfuse_clickhouse_data:
    driver: local
  langfuse_clickhouse_logs:
    driver: local
networks:
  default:
    name: wxo-server
    
