"""
Tests for local authentication modes in the Agentic SDK.

This module tests all the different ways to authenticate in local mode:
1. Explicit local mode with provided token
2. Auto-detected local mode (URL-based)
3. Environment variables with both token and URL
4. Environment variable with URL only (auto-generated token)
5. Zero-config mode (no params, no env vars, auto-generated token)
"""

from __future__ import annotations

import pytest
from unittest.mock import Mock, patch, MagicMock

from ibm_watsonx_orchestrate_sdk import Client
from ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance import (
    DEFAULT_LOCAL_SERVICE_URL,
)


TEST_LOCAL_TOKEN = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJzdWIiOiJmMjQyZWFkZi0wZGM5LTRlYWUtYjJkNy02NWIwOWI0YjRiMTYiLCJ1c2VybmFtZSI6"
    "Ind4by5hcmNoZXJAaWJtLmNvbSIsImF1ZCI6ImF1dGhlbnRpY2F0ZWQiLCJ0ZW5hbnRfaWQiOiI4"
    "ZjUyZmQ0Yy0xMTRiLTRkYmYtOGE0Mi00OTZmOTRlOWE2NDQiLCJ3b1RlbmFudElkIjoiOGY1MmZk"
    "NGMtMTE0Yi00ZGJmLThhNDItNDk2Zjk0ZTlhNjQ0Iiwid29Vc2VySWQiOiJmMjQyZWFkZi0wZGM5"
    "LTRlYWUtYjJkNy02NWIwOWI0YjRiMTYifQ."
    "YQH--ybySHka3e4R6zL3ujPJzLQQaM1JJfrGVi7hQNk"
)


class TestLocalAuthenticationExplicit:
    """Test explicit local mode with provided token."""

    def test_explicit_local_mode_with_token(self):
        """Test: Client(api_key=token, instance_url=url, local=True)"""
        client = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:4321",
            local=True,
        )

        assert client.session.mode == "local"
        assert client.session.base_url == "http://localhost:4321/api/v1"
        assert client.session.access_token == TEST_LOCAL_TOKEN
        assert client.session.authenticator is None

    def test_explicit_local_mode_with_bearer_prefix(self):
        """Test that Bearer prefix is automatically stripped."""
        client = Client(
            api_key=f"Bearer {TEST_LOCAL_TOKEN}",
            instance_url="http://localhost:4321",
            local=True,
        )

        assert client.session.access_token == TEST_LOCAL_TOKEN

    def test_explicit_local_mode_custom_port(self):
        """Test local mode with custom port."""
        client = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:8080",
            local=True,
        )

        assert client.session.base_url == "http://localhost:8080/api/v1"

    def test_explicit_local_mode_with_verify_false(self):
        """Test local mode with SSL verification disabled."""
        client = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:4321",
            local=True,
            verify=False,
        )

        assert client.session.verify is False


class TestLocalAuthenticationAutoDetect:
    """Test auto-detected local mode based on URL patterns."""

    def test_auto_detect_localhost(self):
        """Test auto-detection with localhost URL."""
        client = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:4321",
        )

        assert client.session.mode == "local"
        assert client.session.base_url == "http://localhost:4321/api/v1"

    def test_auto_detect_127_0_0_1(self):
        """Test auto-detection with 127.0.0.1 URL."""
        client = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://127.0.0.1:4321",
        )

        assert client.session.mode == "local"


class TestLocalAuthenticationEnvVars:
    """Test authentication using environment variables."""

    def test_env_vars_both_token_and_url(self, monkeypatch):
        """Test: WXO_USER_TOKEN and WXO_AUTH_URL both set."""
        monkeypatch.setenv("WXO_USER_TOKEN", TEST_LOCAL_TOKEN)
        monkeypatch.setenv("WXO_AUTH_URL", "http://localhost:4321")

        client = Client()

        assert client.session.mode == "local"
        assert client.session.base_url == "http://localhost:4321/api/v1"
        assert client.session.access_token == TEST_LOCAL_TOKEN

    def test_env_vars_with_bearer_prefix(self, monkeypatch):
        """Test that Bearer prefix in env var is stripped."""
        monkeypatch.setenv("WXO_USER_TOKEN", f"Bearer {TEST_LOCAL_TOKEN}")
        monkeypatch.setenv("WXO_AUTH_URL", "http://localhost:4321")

        client = Client()

        assert client.session.access_token == TEST_LOCAL_TOKEN


class TestLocalAuthenticationAutoGenerated:
    """Test auto-generated token scenarios."""

    @patch("ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance.LocalServiceInstance")
    def test_env_url_only_auto_generates_token(self, mock_local_instance, monkeypatch):
        """Test: Only WXO_AUTH_URL set, token auto-generated."""
        monkeypatch.setenv("WXO_AUTH_URL", "http://localhost:4321")
        monkeypatch.delenv("WXO_USER_TOKEN", raising=False)

        # Mock LocalServiceInstance to return a token
        mock_instance = MagicMock()
        mock_instance.tenant_access_token = TEST_LOCAL_TOKEN
        mock_local_instance.return_value = mock_instance

        client = Client()

        assert client.session.mode == "local"
        assert client.session.base_url == "http://localhost:4321/api/v1"
        assert client.session.access_token == TEST_LOCAL_TOKEN
        # Verify LocalServiceInstance was called
        assert mock_local_instance.called

    @patch("ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance.LocalServiceInstance")
    def test_zero_config_uses_default_url_and_auto_generates_token(
        self, mock_local_instance, monkeypatch
    ):
        """Test: No params, no env vars - uses defaults."""
        monkeypatch.delenv("WXO_USER_TOKEN", raising=False)
        monkeypatch.delenv("WXO_AUTH_URL", raising=False)
        monkeypatch.delenv("WXO_AGENTIC_MODE", raising=False)

        # Mock LocalServiceInstance to return a token
        mock_instance = MagicMock()
        mock_instance.tenant_access_token = TEST_LOCAL_TOKEN
        mock_local_instance.return_value = mock_instance

        client = Client()

        assert client.session.mode == "local"
        assert client.session.base_url == f"{DEFAULT_LOCAL_SERVICE_URL}/api/v1"
        assert client.session.access_token == TEST_LOCAL_TOKEN
        # Verify LocalServiceInstance was called
        assert mock_local_instance.called

    @patch("ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance.LocalServiceInstance")
    def test_explicit_local_without_token_auto_generates(self, mock_local_instance):
        """Test: Explicit local=True without token."""
        # Mock LocalServiceInstance to return a token
        mock_instance = MagicMock()
        mock_instance.tenant_access_token = TEST_LOCAL_TOKEN
        mock_local_instance.return_value = mock_instance

        client = Client(
            instance_url="http://localhost:4321",
            local=True,
        )

        assert client.session.mode == "local"
        assert client.session.access_token == TEST_LOCAL_TOKEN
        assert mock_local_instance.called

    @patch("ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance.LocalServiceInstance")
    def test_custom_port_with_auto_generated_token(self, mock_local_instance, monkeypatch):
        """Test: Custom port with auto-generated token."""
        monkeypatch.setenv("WXO_AUTH_URL", "http://localhost:8080")
        monkeypatch.delenv("WXO_USER_TOKEN", raising=False)

        # Mock LocalServiceInstance to return a token
        mock_instance = MagicMock()
        mock_instance.tenant_access_token = TEST_LOCAL_TOKEN
        mock_local_instance.return_value = mock_instance

        client = Client()

        assert client.session.base_url == "http://localhost:8080/api/v1"
        assert client.session.access_token == TEST_LOCAL_TOKEN


class TestLocalAuthenticationEdgeCases:
    """Test edge cases and error conditions."""

    def test_local_mode_respects_verify_parameter(self):
        """Test that verify parameter is passed through."""
        client = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:4321",
            local=True,
            verify="/path/to/cert.pem",
        )

        assert client.session.verify == "/path/to/cert.pem"

    @patch("ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance.LocalServiceInstance")
    def test_auto_generated_token_respects_verify(self, mock_local_instance):
        """Test that verify is passed to token generation."""
        mock_instance = MagicMock()
        mock_instance.tenant_access_token = TEST_LOCAL_TOKEN
        mock_local_instance.return_value = mock_instance

        client = Client(
            instance_url="http://localhost:4321",
            local=True,
            verify=False,
        )

        assert client.session.verify is False

    def test_local_mode_properties_accessible(self):
        """Test that client properties are accessible in local mode."""
        client = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:4321",
            local=True,
        )

        # Should not raise errors
        assert client.session is not None
        assert client.context is not None
        assert client.memory is not None


class TestLocalAuthenticationIntegration:
    """Integration tests for local authentication."""

    def test_all_five_methods_produce_local_mode(self, monkeypatch):
        """Verify all 5 authentication methods result in local mode."""
        
        # Method 1: Explicit
        client1 = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:4321",
            local=True,
        )
        assert client1.session.mode == "local"

        # Method 2: Auto-detect
        client2 = Client(
            api_key=TEST_LOCAL_TOKEN,
            instance_url="http://localhost:4321",
        )
        assert client2.session.mode == "local"

        # Method 3: Env vars (both)
        monkeypatch.setenv("WXO_USER_TOKEN", TEST_LOCAL_TOKEN)
        monkeypatch.setenv("WXO_AUTH_URL", "http://localhost:4321")
        client3 = Client()
        assert client3.session.mode == "local"

    @patch("ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance.LocalServiceInstance")
    def test_methods_4_and_5_with_mocked_token_generation(
        self, mock_local_instance, monkeypatch
    ):
        """Test methods 4 and 5 that require token generation."""
        mock_instance = MagicMock()
        mock_instance.tenant_access_token = TEST_LOCAL_TOKEN
        mock_local_instance.return_value = mock_instance

        # Method 4: Env URL only
        monkeypatch.setenv("WXO_AUTH_URL", "http://localhost:4321")
        monkeypatch.delenv("WXO_USER_TOKEN", raising=False)
        client4 = Client()
        assert client4.session.mode == "local"

        # Method 5: Zero-config
        monkeypatch.delenv("WXO_AUTH_URL", raising=False)
        client5 = Client()
        assert client5.session.mode == "local"
        assert client5.session.base_url == f"{DEFAULT_LOCAL_SERVICE_URL}/api/v1"


class TestLocalAuthenticationConstants:
    """Test that shared constants are used correctly."""

    @patch("ibm_watsonx_orchestrate_clients.common.service_instance.local_service_instance.LocalServiceInstance")
    def test_uses_default_local_service_url_constant(
        self, mock_local_instance, monkeypatch
    ):
        """Verify DEFAULT_LOCAL_SERVICE_URL constant is used."""
        monkeypatch.delenv("WXO_USER_TOKEN", raising=False)
        monkeypatch.delenv("WXO_AUTH_URL", raising=False)

        mock_instance = MagicMock()
        mock_instance.tenant_access_token = TEST_LOCAL_TOKEN
        mock_local_instance.return_value = mock_instance

        client = Client()

        # Should use the constant from LocalServiceInstance
        assert DEFAULT_LOCAL_SERVICE_URL in client.session.base_url
        assert client.session.base_url == f"{DEFAULT_LOCAL_SERVICE_URL}/api/v1"

# Made with Bob
